name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/PULL_REQUEST_TEMPLATE/**'
      - '.github/pull_request_template.md'
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: CI
    runs-on: [self-hosted, stp]
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          java-package: jdk
      - name: Set up fontconfig
        run: |
          sudo apt-get update -y
          curl -LO http://archive.ubuntu.com/ubuntu/pool/main/f/fontconfig/libfontconfig1_2.13.1-4.2ubuntu2_amd64.deb
          curl -LO http://archive.ubuntu.com/ubuntu/pool/main/p/pango1.0/libpangoft2-1.0-0_1.44.7-2ubuntu4_amd64.deb
          sudo dpkg -i libfontconfig1_2.13.1-4.2ubuntu2_amd64.deb libpangoft2-1.0-0_1.44.7-2ubuntu4_amd64.deb
          sudo apt-get install -f -y
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build test jacocoTestReport
      - name: Publish Coverage to Pages
        if: github.event_name != 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/jacoco/test/html/
          destination_dir: ./${{ secrets.COVERAGE_TOKEN }}/coverage/${{ github.ref }}
      - name: Add coverage to PR
        if: github.event_name == 'pull_request'
        uses: madrapps/jacoco-report@v1.3
        with:
          title: '[JaCoCo Report](https://sekassel.github.io/stp-23-team-k/${{ secrets.COVERAGE_TOKEN }}/coverage/${{ github.ref }})'
          paths: build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: ${{ secrets.STP_MIN_COVERAGE }}
